name: portfolio
description: My portfolio
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.3
  build_runner: ^2.4.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  intl: ^0.18.1

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_gen_runner: ^5.4.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter_gen:
  output: lib/gen/

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/pngs/
